Some trying and exploring of possibilities here...

this CountVectorizer is quite useful. It counts the words and represents

- each sentence / email as a row
- each word / term as a column

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

texts = ["blue house and blue window", "window window green house", "green house and blue blue"]

vectorizer = CountVectorizer()
term_count_matrix = vectorizer.fit_transform(texts)

# The unique words / column names
print(vectorizer.get_feature_names()) #in our sklearn version it is get_feature_names, in newer versions it's get_feature_names_out

# Each word"s amount of occurences in texts
print(term_count_matrix.toarray())



['and', 'blue', 'green', 'house', 'window']
[[1 2 0 1 1]
 [0 0 1 1 2]
 [1 2 1 1 0]]


**Looking at our data in data_cooked.csv which looks something like this (example)**


urgent contact last weekend draw show prize call claim code valid,1

get dump heap mom decid come low bore,0

ok lor soni ericsson salesman ask shuhui say quit gd use consid,0

privat account statement show un redeem point call identifi code expir,1


In [61]:
#First get the data
import numpy as np


#I took this from our prepared data and adjusted a bit to illustrate better
data= np.array([
("free claim call code", 1),
("heap mom bore",0),
("ok salesman quit",0),
("urgent call free identifi code",1)
])

mails = data[:,0] #all rows, 0th column
labels = data[:,1] #all rows, 1st column


# Second: use the vectorizer on the mails
vectorizer = CountVectorizer()
word_count_matrix = vectorizer.fit_transform(mails)
print('Word Count Matrix looks like this:\n', word_count_matrix.toarray())




Word Count Matrix looks like this:
 [[0 1 1 1 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 0]
 [0 1 0 1 1 0 1 0 0 0 0 1]]


as a next step, we can calculating:

for each word (meaning for each column): Count how often the word appears in a spam sentence and then calculate its probability as 

Occurences in Spam Mails  /  Amount all mails

In [63]:
probabilities = {}


number_all_mails = len(word_count_matrix.toarray())
for index,word in enumerate(vectorizer.get_feature_names()):
    column = word_count_matrix[:,index]
    count = np.count_nonzero(column[column>0]) # column[column>0] makes column a 1D array of True and False values 
    probabilities[word] = count / number_all_mails

probabilities


{'bore': 0.25,
 'call': 0.5,
 'claim': 0.25,
 'code': 0.5,
 'free': 0.5,
 'heap': 0.25,
 'identifi': 0.25,
 'mom': 0.25,
 'ok': 0.25,
 'quit': 0.25,
 'salesman': 0.25,
 'urgent': 0.25}

See how words like call, code, free are rated higher than other words

it's still very simple the way it is but could be a start 